/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendasSimuladorRouteImport } from './routes/vendas.simulador'
import { Route as VendasOrcamentosRouteImport } from './routes/vendas.orcamentos'
import { Route as VendasHistoricoRouteImport } from './routes/vendas.historico'
import { Route as VendasGarantiasRouteImport } from './routes/vendas.garantias'
import { Route as VendasDeliveryRouteImport } from './routes/vendas.delivery'
import { Route as VendasConsultaEstoqueRouteImport } from './routes/vendas.consulta-estoque'
import { Route as VendasCalculadoraRouteImport } from './routes/vendas.calculadora'
import { Route as ServicosTermosRouteImport } from './routes/servicos.termos'
import { Route as ServicosTecnicosRouteImport } from './routes/servicos.tecnicos'
import { Route as ServicosNovaRouteImport } from './routes/servicos.nova'
import { Route as ServicosDashboardRouteImport } from './routes/servicos.dashboard'
import { Route as ServicosChecklistsRouteImport } from './routes/servicos.checklists'
import { Route as FinanceiroPlanoContasRouteImport } from './routes/financeiro.plano-contas'
import { Route as FinanceiroMaquininhasRouteImport } from './routes/financeiro.maquininhas'
import { Route as FinanceiroFornecedoresRouteImport } from './routes/financeiro.fornecedores'
import { Route as FinanceiroDreRouteImport } from './routes/financeiro.dre'
import { Route as FinanceiroCaixaRouteImport } from './routes/financeiro.caixa'
import { Route as EstoqueVendidosRouteImport } from './routes/estoque.vendidos'
import { Route as EstoqueMovimentacoesRouteImport } from './routes/estoque.movimentacoes'
import { Route as EstoqueEtiquetasRouteImport } from './routes/estoque.etiquetas'
import { Route as EstoqueComprasRouteImport } from './routes/estoque.compras'
import { Route as EstoqueAtualRouteImport } from './routes/estoque.atual'
import { Route as CrmBotRouteImport } from './routes/crm.bot'
import { Route as AppRelatoriosIndexRouteImport } from './routes/_app/relatorios/index'
import { Route as AppMarketingIndexRouteImport } from './routes/_app/marketing/index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes/index'
import { Route as AppAgendamentosIndexRouteImport } from './routes/_app/agendamentos/index'
import { Route as ApiEvolutionSplatRouteImport } from './routes/api/evolution/$'
import { Route as AppOperacaoTransportadoresRouteImport } from './routes/_app/operacao/transportadores'
import { Route as AppOperacaoTiposProdutosRouteImport } from './routes/_app/operacao/tipos-produtos'
import { Route as AppOperacaoServicosRouteImport } from './routes/_app/operacao/servicos'
import { Route as AppOperacaoMaquininhasRouteImport } from './routes/_app/operacao/maquininhas'
import { Route as AppFinanceiroContasReceberRouteImport } from './routes/_app/financeiro/contas-receber'
import { Route as AppFinanceiroContasPagarRouteImport } from './routes/_app/financeiro/contas-pagar'
import { Route as AppConfiguracoesParametrosRouteImport } from './routes/_app/configuracoes/parametros'
import { Route as AppClientesNovoRouteImport } from './routes/_app/clientes/novo'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/whatsapp.lazy').then((d) => d.Route))
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasSimuladorRoute = VendasSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => VendasRoute,
} as any)
const VendasOrcamentosRoute = VendasOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => VendasRoute,
} as any)
const VendasHistoricoRoute = VendasHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => VendasRoute,
} as any)
const VendasGarantiasRoute = VendasGarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => VendasRoute,
} as any)
const VendasDeliveryRoute = VendasDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => VendasRoute,
} as any)
const VendasConsultaEstoqueRoute = VendasConsultaEstoqueRouteImport.update({
  id: '/consulta-estoque',
  path: '/consulta-estoque',
  getParentRoute: () => VendasRoute,
} as any)
const VendasCalculadoraRoute = VendasCalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => VendasRoute,
} as any)
const ServicosTermosRoute = ServicosTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosTecnicosRoute = ServicosTecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosNovaRoute = ServicosNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosDashboardRoute = ServicosDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosChecklistsRoute = ServicosChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => ServicosRoute,
} as any)
const FinanceiroPlanoContasRoute = FinanceiroPlanoContasRouteImport.update({
  id: '/plano-contas',
  path: '/plano-contas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroMaquininhasRoute = FinanceiroMaquininhasRouteImport.update({
  id: '/maquininhas',
  path: '/maquininhas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroFornecedoresRoute = FinanceiroFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroDreRoute = FinanceiroDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroCaixaRoute = FinanceiroCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => FinanceiroRoute,
} as any)
const EstoqueVendidosRoute = EstoqueVendidosRouteImport.update({
  id: '/vendidos',
  path: '/vendidos',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueMovimentacoesRoute = EstoqueMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueEtiquetasRoute = EstoqueEtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueComprasRoute = EstoqueComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueAtualRoute = EstoqueAtualRouteImport.update({
  id: '/atual',
  path: '/atual',
  getParentRoute: () => EstoqueRoute,
} as any)
const CrmBotRoute = CrmBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => CrmRoute,
} as any)
const AppRelatoriosIndexRoute = AppRelatoriosIndexRouteImport.update({
  id: '/_app/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMarketingIndexRoute = AppMarketingIndexRouteImport.update({
  id: '/_app/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/_app/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendamentosIndexRoute = AppAgendamentosIndexRouteImport.update({
  id: '/_app/agendamentos/',
  path: '/agendamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionSplatRoute = ApiEvolutionSplatRouteImport.update({
  id: '/api/evolution/$',
  path: '/api/evolution/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOperacaoTransportadoresRoute =
  AppOperacaoTransportadoresRouteImport.update({
    id: '/_app/operacao/transportadores',
    path: '/operacao/transportadores',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOperacaoTiposProdutosRoute =
  AppOperacaoTiposProdutosRouteImport.update({
    id: '/_app/operacao/tipos-produtos',
    path: '/operacao/tipos-produtos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOperacaoServicosRoute = AppOperacaoServicosRouteImport.update({
  id: '/_app/operacao/servicos',
  path: '/operacao/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOperacaoMaquininhasRoute = AppOperacaoMaquininhasRouteImport.update({
  id: '/_app/operacao/maquininhas',
  path: '/operacao/maquininhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFinanceiroContasReceberRoute =
  AppFinanceiroContasReceberRouteImport.update({
    id: '/_app/financeiro/contas-receber',
    path: '/financeiro/contas-receber',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppFinanceiroContasPagarRoute =
  AppFinanceiroContasPagarRouteImport.update({
    id: '/_app/financeiro/contas-pagar',
    path: '/financeiro/contas-pagar',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppConfiguracoesParametrosRoute =
  AppConfiguracoesParametrosRouteImport.update({
    id: '/_app/configuracoes/parametros',
    path: '/configuracoes/parametros',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/_app/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/atendimento': typeof AtendimentoRoute
  '/automacao': typeof AutomacaoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/funil': typeof FunilRoute
  '/instagram': typeof InstagramRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/vendas': typeof VendasRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/crm/bot': typeof CrmBotRoute
  '/estoque/atual': typeof EstoqueAtualRoute
  '/estoque/compras': typeof EstoqueComprasRoute
  '/estoque/etiquetas': typeof EstoqueEtiquetasRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/vendidos': typeof EstoqueVendidosRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fornecedores': typeof FinanceiroFornecedoresRoute
  '/financeiro/maquininhas': typeof FinanceiroMaquininhasRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/servicos/checklists': typeof ServicosChecklistsRoute
  '/servicos/dashboard': typeof ServicosDashboardRoute
  '/servicos/nova': typeof ServicosNovaRoute
  '/servicos/tecnicos': typeof ServicosTecnicosRoute
  '/servicos/termos': typeof ServicosTermosRoute
  '/vendas/calculadora': typeof VendasCalculadoraRoute
  '/vendas/consulta-estoque': typeof VendasConsultaEstoqueRoute
  '/vendas/delivery': typeof VendasDeliveryRoute
  '/vendas/garantias': typeof VendasGarantiasRoute
  '/vendas/historico': typeof VendasHistoricoRoute
  '/vendas/orcamentos': typeof VendasOrcamentosRoute
  '/vendas/simulador': typeof VendasSimuladorRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/configuracoes/parametros': typeof AppConfiguracoesParametrosRoute
  '/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof AppFinanceiroContasReceberRoute
  '/operacao/maquininhas': typeof AppOperacaoMaquininhasRoute
  '/operacao/servicos': typeof AppOperacaoServicosRoute
  '/operacao/tipos-produtos': typeof AppOperacaoTiposProdutosRoute
  '/operacao/transportadores': typeof AppOperacaoTransportadoresRoute
  '/api/evolution/$': typeof ApiEvolutionSplatRoute
  '/agendamentos/': typeof AppAgendamentosIndexRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/marketing/': typeof AppMarketingIndexRoute
  '/relatorios/': typeof AppRelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/atendimento': typeof AtendimentoRoute
  '/automacao': typeof AutomacaoRoute
  '/clientes': typeof AppClientesIndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/funil': typeof FunilRoute
  '/instagram': typeof InstagramRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof AppRelatoriosIndexRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/vendas': typeof VendasRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/crm/bot': typeof CrmBotRoute
  '/estoque/atual': typeof EstoqueAtualRoute
  '/estoque/compras': typeof EstoqueComprasRoute
  '/estoque/etiquetas': typeof EstoqueEtiquetasRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/vendidos': typeof EstoqueVendidosRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fornecedores': typeof FinanceiroFornecedoresRoute
  '/financeiro/maquininhas': typeof FinanceiroMaquininhasRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/servicos/checklists': typeof ServicosChecklistsRoute
  '/servicos/dashboard': typeof ServicosDashboardRoute
  '/servicos/nova': typeof ServicosNovaRoute
  '/servicos/tecnicos': typeof ServicosTecnicosRoute
  '/servicos/termos': typeof ServicosTermosRoute
  '/vendas/calculadora': typeof VendasCalculadoraRoute
  '/vendas/consulta-estoque': typeof VendasConsultaEstoqueRoute
  '/vendas/delivery': typeof VendasDeliveryRoute
  '/vendas/garantias': typeof VendasGarantiasRoute
  '/vendas/historico': typeof VendasHistoricoRoute
  '/vendas/orcamentos': typeof VendasOrcamentosRoute
  '/vendas/simulador': typeof VendasSimuladorRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/configuracoes/parametros': typeof AppConfiguracoesParametrosRoute
  '/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof AppFinanceiroContasReceberRoute
  '/operacao/maquininhas': typeof AppOperacaoMaquininhasRoute
  '/operacao/servicos': typeof AppOperacaoServicosRoute
  '/operacao/tipos-produtos': typeof AppOperacaoTiposProdutosRoute
  '/operacao/transportadores': typeof AppOperacaoTransportadoresRoute
  '/api/evolution/$': typeof ApiEvolutionSplatRoute
  '/agendamentos': typeof AppAgendamentosIndexRoute
  '/marketing': typeof AppMarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/atendimento': typeof AtendimentoRoute
  '/automacao': typeof AutomacaoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/funil': typeof FunilRoute
  '/instagram': typeof InstagramRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/vendas': typeof VendasRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/crm/bot': typeof CrmBotRoute
  '/estoque/atual': typeof EstoqueAtualRoute
  '/estoque/compras': typeof EstoqueComprasRoute
  '/estoque/etiquetas': typeof EstoqueEtiquetasRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/vendidos': typeof EstoqueVendidosRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fornecedores': typeof FinanceiroFornecedoresRoute
  '/financeiro/maquininhas': typeof FinanceiroMaquininhasRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/servicos/checklists': typeof ServicosChecklistsRoute
  '/servicos/dashboard': typeof ServicosDashboardRoute
  '/servicos/nova': typeof ServicosNovaRoute
  '/servicos/tecnicos': typeof ServicosTecnicosRoute
  '/servicos/termos': typeof ServicosTermosRoute
  '/vendas/calculadora': typeof VendasCalculadoraRoute
  '/vendas/consulta-estoque': typeof VendasConsultaEstoqueRoute
  '/vendas/delivery': typeof VendasDeliveryRoute
  '/vendas/garantias': typeof VendasGarantiasRoute
  '/vendas/historico': typeof VendasHistoricoRoute
  '/vendas/orcamentos': typeof VendasOrcamentosRoute
  '/vendas/simulador': typeof VendasSimuladorRoute
  '/_app/clientes/novo': typeof AppClientesNovoRoute
  '/_app/configuracoes/parametros': typeof AppConfiguracoesParametrosRoute
  '/_app/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/_app/financeiro/contas-receber': typeof AppFinanceiroContasReceberRoute
  '/_app/operacao/maquininhas': typeof AppOperacaoMaquininhasRoute
  '/_app/operacao/servicos': typeof AppOperacaoServicosRoute
  '/_app/operacao/tipos-produtos': typeof AppOperacaoTiposProdutosRoute
  '/_app/operacao/transportadores': typeof AppOperacaoTransportadoresRoute
  '/api/evolution/$': typeof ApiEvolutionSplatRoute
  '/_app/agendamentos/': typeof AppAgendamentosIndexRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/marketing/': typeof AppMarketingIndexRoute
  '/_app/relatorios/': typeof AppRelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/atendimento'
    | '/automacao'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/funil'
    | '/instagram'
    | '/leads'
    | '/login'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/servicos'
    | '/vendas'
    | '/whatsapp'
    | '/crm/bot'
    | '/estoque/atual'
    | '/estoque/compras'
    | '/estoque/etiquetas'
    | '/estoque/movimentacoes'
    | '/estoque/vendidos'
    | '/financeiro/caixa'
    | '/financeiro/dre'
    | '/financeiro/fornecedores'
    | '/financeiro/maquininhas'
    | '/financeiro/plano-contas'
    | '/servicos/checklists'
    | '/servicos/dashboard'
    | '/servicos/nova'
    | '/servicos/tecnicos'
    | '/servicos/termos'
    | '/vendas/calculadora'
    | '/vendas/consulta-estoque'
    | '/vendas/delivery'
    | '/vendas/garantias'
    | '/vendas/historico'
    | '/vendas/orcamentos'
    | '/vendas/simulador'
    | '/clientes/novo'
    | '/configuracoes/parametros'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/operacao/maquininhas'
    | '/operacao/servicos'
    | '/operacao/tipos-produtos'
    | '/operacao/transportadores'
    | '/api/evolution/$'
    | '/agendamentos/'
    | '/clientes/'
    | '/marketing/'
    | '/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/atendimento'
    | '/automacao'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/funil'
    | '/instagram'
    | '/leads'
    | '/login'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/servicos'
    | '/vendas'
    | '/whatsapp'
    | '/crm/bot'
    | '/estoque/atual'
    | '/estoque/compras'
    | '/estoque/etiquetas'
    | '/estoque/movimentacoes'
    | '/estoque/vendidos'
    | '/financeiro/caixa'
    | '/financeiro/dre'
    | '/financeiro/fornecedores'
    | '/financeiro/maquininhas'
    | '/financeiro/plano-contas'
    | '/servicos/checklists'
    | '/servicos/dashboard'
    | '/servicos/nova'
    | '/servicos/tecnicos'
    | '/servicos/termos'
    | '/vendas/calculadora'
    | '/vendas/consulta-estoque'
    | '/vendas/delivery'
    | '/vendas/garantias'
    | '/vendas/historico'
    | '/vendas/orcamentos'
    | '/vendas/simulador'
    | '/clientes/novo'
    | '/configuracoes/parametros'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/operacao/maquininhas'
    | '/operacao/servicos'
    | '/operacao/tipos-produtos'
    | '/operacao/transportadores'
    | '/api/evolution/$'
    | '/agendamentos'
    | '/marketing'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/atendimento'
    | '/automacao'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/funil'
    | '/instagram'
    | '/leads'
    | '/login'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/servicos'
    | '/vendas'
    | '/whatsapp'
    | '/crm/bot'
    | '/estoque/atual'
    | '/estoque/compras'
    | '/estoque/etiquetas'
    | '/estoque/movimentacoes'
    | '/estoque/vendidos'
    | '/financeiro/caixa'
    | '/financeiro/dre'
    | '/financeiro/fornecedores'
    | '/financeiro/maquininhas'
    | '/financeiro/plano-contas'
    | '/servicos/checklists'
    | '/servicos/dashboard'
    | '/servicos/nova'
    | '/servicos/tecnicos'
    | '/servicos/termos'
    | '/vendas/calculadora'
    | '/vendas/consulta-estoque'
    | '/vendas/delivery'
    | '/vendas/garantias'
    | '/vendas/historico'
    | '/vendas/orcamentos'
    | '/vendas/simulador'
    | '/_app/clientes/novo'
    | '/_app/configuracoes/parametros'
    | '/_app/financeiro/contas-pagar'
    | '/_app/financeiro/contas-receber'
    | '/_app/operacao/maquininhas'
    | '/_app/operacao/servicos'
    | '/_app/operacao/tipos-produtos'
    | '/_app/operacao/transportadores'
    | '/api/evolution/$'
    | '/_app/agendamentos/'
    | '/_app/clientes/'
    | '/_app/marketing/'
    | '/_app/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  AtendimentoRoute: typeof AtendimentoRoute
  AutomacaoRoute: typeof AutomacaoRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CrmRoute: typeof CrmRouteWithChildren
  EquipeRoute: typeof EquipeRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  FiscalRoute: typeof FiscalRoute
  FunilRoute: typeof FunilRoute
  InstagramRoute: typeof InstagramRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PdvRoute: typeof PdvRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  VendasRoute: typeof VendasRouteWithChildren
  WhatsappRoute: typeof WhatsappRoute
  AppClientesNovoRoute: typeof AppClientesNovoRoute
  AppConfiguracoesParametrosRoute: typeof AppConfiguracoesParametrosRoute
  AppFinanceiroContasPagarRoute: typeof AppFinanceiroContasPagarRoute
  AppFinanceiroContasReceberRoute: typeof AppFinanceiroContasReceberRoute
  AppOperacaoMaquininhasRoute: typeof AppOperacaoMaquininhasRoute
  AppOperacaoServicosRoute: typeof AppOperacaoServicosRoute
  AppOperacaoTiposProdutosRoute: typeof AppOperacaoTiposProdutosRoute
  AppOperacaoTransportadoresRoute: typeof AppOperacaoTransportadoresRoute
  ApiEvolutionSplatRoute: typeof ApiEvolutionSplatRoute
  AppAgendamentosIndexRoute: typeof AppAgendamentosIndexRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppMarketingIndexRoute: typeof AppMarketingIndexRoute
  AppRelatoriosIndexRoute: typeof AppRelatoriosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/simulador': {
      id: '/vendas/simulador'
      path: '/simulador'
      fullPath: '/vendas/simulador'
      preLoaderRoute: typeof VendasSimuladorRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/orcamentos': {
      id: '/vendas/orcamentos'
      path: '/orcamentos'
      fullPath: '/vendas/orcamentos'
      preLoaderRoute: typeof VendasOrcamentosRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/historico': {
      id: '/vendas/historico'
      path: '/historico'
      fullPath: '/vendas/historico'
      preLoaderRoute: typeof VendasHistoricoRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/garantias': {
      id: '/vendas/garantias'
      path: '/garantias'
      fullPath: '/vendas/garantias'
      preLoaderRoute: typeof VendasGarantiasRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/delivery': {
      id: '/vendas/delivery'
      path: '/delivery'
      fullPath: '/vendas/delivery'
      preLoaderRoute: typeof VendasDeliveryRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/consulta-estoque': {
      id: '/vendas/consulta-estoque'
      path: '/consulta-estoque'
      fullPath: '/vendas/consulta-estoque'
      preLoaderRoute: typeof VendasConsultaEstoqueRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/calculadora': {
      id: '/vendas/calculadora'
      path: '/calculadora'
      fullPath: '/vendas/calculadora'
      preLoaderRoute: typeof VendasCalculadoraRouteImport
      parentRoute: typeof VendasRoute
    }
    '/servicos/termos': {
      id: '/servicos/termos'
      path: '/termos'
      fullPath: '/servicos/termos'
      preLoaderRoute: typeof ServicosTermosRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/tecnicos': {
      id: '/servicos/tecnicos'
      path: '/tecnicos'
      fullPath: '/servicos/tecnicos'
      preLoaderRoute: typeof ServicosTecnicosRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/nova': {
      id: '/servicos/nova'
      path: '/nova'
      fullPath: '/servicos/nova'
      preLoaderRoute: typeof ServicosNovaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/dashboard': {
      id: '/servicos/dashboard'
      path: '/dashboard'
      fullPath: '/servicos/dashboard'
      preLoaderRoute: typeof ServicosDashboardRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/checklists': {
      id: '/servicos/checklists'
      path: '/checklists'
      fullPath: '/servicos/checklists'
      preLoaderRoute: typeof ServicosChecklistsRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/financeiro/plano-contas': {
      id: '/financeiro/plano-contas'
      path: '/plano-contas'
      fullPath: '/financeiro/plano-contas'
      preLoaderRoute: typeof FinanceiroPlanoContasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/maquininhas': {
      id: '/financeiro/maquininhas'
      path: '/maquininhas'
      fullPath: '/financeiro/maquininhas'
      preLoaderRoute: typeof FinanceiroMaquininhasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/fornecedores': {
      id: '/financeiro/fornecedores'
      path: '/fornecedores'
      fullPath: '/financeiro/fornecedores'
      preLoaderRoute: typeof FinanceiroFornecedoresRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/dre': {
      id: '/financeiro/dre'
      path: '/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof FinanceiroDreRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/caixa': {
      id: '/financeiro/caixa'
      path: '/caixa'
      fullPath: '/financeiro/caixa'
      preLoaderRoute: typeof FinanceiroCaixaRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/estoque/vendidos': {
      id: '/estoque/vendidos'
      path: '/vendidos'
      fullPath: '/estoque/vendidos'
      preLoaderRoute: typeof EstoqueVendidosRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/movimentacoes': {
      id: '/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof EstoqueMovimentacoesRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/etiquetas': {
      id: '/estoque/etiquetas'
      path: '/etiquetas'
      fullPath: '/estoque/etiquetas'
      preLoaderRoute: typeof EstoqueEtiquetasRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/compras': {
      id: '/estoque/compras'
      path: '/compras'
      fullPath: '/estoque/compras'
      preLoaderRoute: typeof EstoqueComprasRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/atual': {
      id: '/estoque/atual'
      path: '/atual'
      fullPath: '/estoque/atual'
      preLoaderRoute: typeof EstoqueAtualRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/crm/bot': {
      id: '/crm/bot'
      path: '/bot'
      fullPath: '/crm/bot'
      preLoaderRoute: typeof CrmBotRouteImport
      parentRoute: typeof CrmRoute
    }
    '/_app/relatorios/': {
      id: '/_app/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AppRelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/marketing/': {
      id: '/_app/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AppMarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agendamentos/': {
      id: '/_app/agendamentos/'
      path: '/agendamentos'
      fullPath: '/agendamentos/'
      preLoaderRoute: typeof AppAgendamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution/$': {
      id: '/api/evolution/$'
      path: '/api/evolution/$'
      fullPath: '/api/evolution/$'
      preLoaderRoute: typeof ApiEvolutionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/operacao/transportadores': {
      id: '/_app/operacao/transportadores'
      path: '/operacao/transportadores'
      fullPath: '/operacao/transportadores'
      preLoaderRoute: typeof AppOperacaoTransportadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/operacao/tipos-produtos': {
      id: '/_app/operacao/tipos-produtos'
      path: '/operacao/tipos-produtos'
      fullPath: '/operacao/tipos-produtos'
      preLoaderRoute: typeof AppOperacaoTiposProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/operacao/servicos': {
      id: '/_app/operacao/servicos'
      path: '/operacao/servicos'
      fullPath: '/operacao/servicos'
      preLoaderRoute: typeof AppOperacaoServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/operacao/maquininhas': {
      id: '/_app/operacao/maquininhas'
      path: '/operacao/maquininhas'
      fullPath: '/operacao/maquininhas'
      preLoaderRoute: typeof AppOperacaoMaquininhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/financeiro/contas-receber': {
      id: '/_app/financeiro/contas-receber'
      path: '/financeiro/contas-receber'
      fullPath: '/financeiro/contas-receber'
      preLoaderRoute: typeof AppFinanceiroContasReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/financeiro/contas-pagar': {
      id: '/_app/financeiro/contas-pagar'
      path: '/financeiro/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof AppFinanceiroContasPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/configuracoes/parametros': {
      id: '/_app/configuracoes/parametros'
      path: '/configuracoes/parametros'
      fullPath: '/configuracoes/parametros'
      preLoaderRoute: typeof AppConfiguracoesParametrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clientes/novo': {
      id: '/_app/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmRouteChildren {
  CrmBotRoute: typeof CrmBotRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmBotRoute: CrmBotRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface EstoqueRouteChildren {
  EstoqueAtualRoute: typeof EstoqueAtualRoute
  EstoqueComprasRoute: typeof EstoqueComprasRoute
  EstoqueEtiquetasRoute: typeof EstoqueEtiquetasRoute
  EstoqueMovimentacoesRoute: typeof EstoqueMovimentacoesRoute
  EstoqueVendidosRoute: typeof EstoqueVendidosRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueAtualRoute: EstoqueAtualRoute,
  EstoqueComprasRoute: EstoqueComprasRoute,
  EstoqueEtiquetasRoute: EstoqueEtiquetasRoute,
  EstoqueMovimentacoesRoute: EstoqueMovimentacoesRoute,
  EstoqueVendidosRoute: EstoqueVendidosRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

interface FinanceiroRouteChildren {
  FinanceiroCaixaRoute: typeof FinanceiroCaixaRoute
  FinanceiroDreRoute: typeof FinanceiroDreRoute
  FinanceiroFornecedoresRoute: typeof FinanceiroFornecedoresRoute
  FinanceiroMaquininhasRoute: typeof FinanceiroMaquininhasRoute
  FinanceiroPlanoContasRoute: typeof FinanceiroPlanoContasRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroCaixaRoute: FinanceiroCaixaRoute,
  FinanceiroDreRoute: FinanceiroDreRoute,
  FinanceiroFornecedoresRoute: FinanceiroFornecedoresRoute,
  FinanceiroMaquininhasRoute: FinanceiroMaquininhasRoute,
  FinanceiroPlanoContasRoute: FinanceiroPlanoContasRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface ServicosRouteChildren {
  ServicosChecklistsRoute: typeof ServicosChecklistsRoute
  ServicosDashboardRoute: typeof ServicosDashboardRoute
  ServicosNovaRoute: typeof ServicosNovaRoute
  ServicosTecnicosRoute: typeof ServicosTecnicosRoute
  ServicosTermosRoute: typeof ServicosTermosRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosChecklistsRoute: ServicosChecklistsRoute,
  ServicosDashboardRoute: ServicosDashboardRoute,
  ServicosNovaRoute: ServicosNovaRoute,
  ServicosTecnicosRoute: ServicosTecnicosRoute,
  ServicosTermosRoute: ServicosTermosRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

interface VendasRouteChildren {
  VendasCalculadoraRoute: typeof VendasCalculadoraRoute
  VendasConsultaEstoqueRoute: typeof VendasConsultaEstoqueRoute
  VendasDeliveryRoute: typeof VendasDeliveryRoute
  VendasGarantiasRoute: typeof VendasGarantiasRoute
  VendasHistoricoRoute: typeof VendasHistoricoRoute
  VendasOrcamentosRoute: typeof VendasOrcamentosRoute
  VendasSimuladorRoute: typeof VendasSimuladorRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasCalculadoraRoute: VendasCalculadoraRoute,
  VendasConsultaEstoqueRoute: VendasConsultaEstoqueRoute,
  VendasDeliveryRoute: VendasDeliveryRoute,
  VendasGarantiasRoute: VendasGarantiasRoute,
  VendasHistoricoRoute: VendasHistoricoRoute,
  VendasOrcamentosRoute: VendasOrcamentosRoute,
  VendasSimuladorRoute: VendasSimuladorRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  AtendimentoRoute: AtendimentoRoute,
  AutomacaoRoute: AutomacaoRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CrmRoute: CrmRouteWithChildren,
  EquipeRoute: EquipeRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  FiscalRoute: FiscalRoute,
  FunilRoute: FunilRoute,
  InstagramRoute: InstagramRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PdvRoute: PdvRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ServicosRoute: ServicosRouteWithChildren,
  VendasRoute: VendasRouteWithChildren,
  WhatsappRoute: WhatsappRoute,
  AppClientesNovoRoute: AppClientesNovoRoute,
  AppConfiguracoesParametrosRoute: AppConfiguracoesParametrosRoute,
  AppFinanceiroContasPagarRoute: AppFinanceiroContasPagarRoute,
  AppFinanceiroContasReceberRoute: AppFinanceiroContasReceberRoute,
  AppOperacaoMaquininhasRoute: AppOperacaoMaquininhasRoute,
  AppOperacaoServicosRoute: AppOperacaoServicosRoute,
  AppOperacaoTiposProdutosRoute: AppOperacaoTiposProdutosRoute,
  AppOperacaoTransportadoresRoute: AppOperacaoTransportadoresRoute,
  ApiEvolutionSplatRoute: ApiEvolutionSplatRoute,
  AppAgendamentosIndexRoute: AppAgendamentosIndexRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppMarketingIndexRoute: AppMarketingIndexRoute,
  AppRelatoriosIndexRoute: AppRelatoriosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
